g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcapimin.c -o jcapimin.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcapistd.c -o jcapistd.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jccoefct.c -o jccoefct.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jccolor.c  -o jccolor.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcdctmgr.c -o jcdctmgr.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jchuff.c   -o jchuff.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcinit.c   -o jcinit.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcmainct.c -o jcmainct.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcmarker.c -o jcmarker.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcmaster.c -o jcmaster.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcomapi.c  -o jcomapi.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcparam.c  -o jcparam.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcphuff.c  -o jcphuff.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcprepct.c -o jcprepct.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jcsample.c -o jcsample.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jctrans.c  -o jctrans.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdapimin.c -o jdapimin.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdatadst.c -o jdatadst.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdcoefct.c -o jdcoefct.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdcolor.c  -o jdcolor.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jddctmgr.c -o jddctmgr.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdinput.c  -o jdinput.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdmainct.c -o jdmainct.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdmarker.c -o jdmarker.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdmerge.c  -o jdmerge.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdpostct.c -o jdpostct.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jdsample.c -o jdsample.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jerror.c   -o jerror.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jfdctflt.c -o jfdctflt.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jfdctfst.c -o jfdctfst.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jfdctint.c -o jfdctint.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jidctflt.c -o jidctflt.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jidctfst.c -o jidctfst.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jidctint.c -o jidctint.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jidctred.c -o jidctred.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jmemansi.c -o jmemansi.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jmemmgr.c  -o jmemmgr.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jquant1.c  -o jquant1.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jquant2.c  -o jquant2.o
g++ -W -std=c99   -O3 -march=native -I./jpeg-6b -x c -c jpeg-6b/jutils.c   -o jutils.o
g++ -Wall -Wextra -pedantic -std=c++17 -O3 -march=native -IC:/boost/boost_1_72_0 -I./jpeg-6b -c mandelbrot.cpp     -o mandelbrot.o
g++ -Wall -Wextra -pedantic -std=c++17 -O3 -march=native jcapimin.o jcapistd.o jccoefct.o jccolor.o  jcdctmgr.o jchuff.o   jcinit.o   jcmainct.o jcmarker.o jcmaster.o jcomapi.o  jcparam.o  jcphuff.o  jcprepct.o jcsample.o jctrans.o  jdapimin.o jdatadst.o jdcoefct.o jdcolor.o  jddctmgr.o jdinput.o  jdmainct.o jdmarker.o jdmerge.o  jdpostct.o jdsample.o jerror.o   jfdctflt.o jfdctfst.o jfdctint.o jidctflt.o jidctfst.o jidctint.o jidctred.o jmemansi.o jmemmgr.o  jquant1.o  jquant2.o  jutils.o mandelbrot.o -o mandelbrot.exe
